### ISSUE TITLE
longest_run_ones_in_a_block_test fails with small dataset 

### ISSUE THREAD

**Issue by karthikkrishnanv** [dj-on-github/sp800_22_tests#10]
bits = np.random.randint(2, size=120)

For small dataset, longest_run_ones_in_a_block_test doesn't fail correctly and causes run to stop

`def longest_run_ones_in_a_block_test(bits):
    n = len(bits)

    if n < 128:
        #return 0 [Current]
        return (None,None,None)`

**Comment by dj-on-github** [comment]
Thank you for catching that. I've fixed it. I returned (False,1.0,None) to indicate a failure when n < 128.
