### ISSUE TITLE
Overall test script stops with small dataset

### ISSUE THREAD

**Issue by renatosc** [dj-on-github/sp800_22_tests#11]
This is similar to issue #10 , but for tests [sp800_22_linear_complexity_test.py](https://github.com/dj-on-github/sp800_22_tests/blob/master/sp800_22_linear_complexity_test.py#L64) and [sp800_22_maurers_universal_test.py](https://github.com/dj-on-github/sp800_22_tests/blob/master/sp800_22_maurers_universal_test.py#L47).

Right now, those 2 tests terminates (exit()) the running script if the dataset is too small. As fixed on issue #10, they would work best if just return a fail test (return False), so it doesn't terminate the python script sp800_22_tests.py.

**Comment by dj-on-github** [comment]
Done. The two tests fail but return as you described.
