### ISSUE TITLE
In Random Excursion Variant Test, P-value Should Be Calculated Using Erfc

### ISSUE THREAD

**Issue by nategri** [dj-on-github/sp800_22_tests#17]
See pg. 2-39 of the reference material:

https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-22r1a.pdf

Basically it seems that what's currently calculated as p should be passed into an erfc function, and then THAT will be the actual p.

![Screenshot 2019-10-30 17 27 43](https://user-images.githubusercontent.com/4634208/67908946-98199880-fb3a-11e9-8014-7a9182e80e96.png)

**Comment by dj-on-github** [comment]
Thank you. I've added the erfc.
