### ISSUE TITLE
Cannot generate random numbers

### ISSUE THREAD

**Issue by zhliao** [dj-on-github/sp800_22_tests#18]
Hi,

I tried to do the NIST randomnes test and have downloaded the source file for both sp test and djenrandom, and compiled it using the makefile. When I type the command:
./djenrandom -b -k 128 > megabitrand.bin

The system outputs an error:

Failed to open YAML output file  for writing
: No such file or directory

I am not sure if there any thing worng. Could you give me any advice? Thanks

**Comment by dj-on-github** [comment]
That's odd. The YAML output should require the yaml option. I'll go look.

**Comment by dj-on-github** [comment]
modelstate.using_yaml was uninitialized. Shame on me.

The fix is in. Let me know if it works.
