### ISSUE TITLE
about binary_matrix_rank_test

### ISSUE THREAD

**Issue by miuchen** [dj-on-github/sp800_22_tests#2]
SUMMARY
-------
monobit_test                             0.581114294834     PASS
frequency_within_block_test              0.747793618708     PASS
runs_test                                0.842033492763     PASS
longest_run_ones_in_a_block_test         0.863705090529     PASS
binary_matrix_rank_test                  0.0359437277529    FAIL

in the source code:

    p = math.e **(-chisq/2.0)
    success = (p >= 0.1)

why 0.1，i think maybe 0.01？

**Comment by dj-on-github** [comment]
You are correct. I checked the spec. I've fixed it and changed threshold to 0.01.
Thanks.
