### ISSUE TITLE
About sp800_22_monobit_test

### ISSUE THREAD

**Issue by jubollow** [dj-on-github/sp800_22_tests#3]
hi 

Thank you for converting sp800-22 to python code.

I am using this program very usefully.

The p-value criterion of sp800_22_monobit_test.py is set to 0.1.

Is not 0.01 correct?

**Comment by dj-on-github** [comment]
Yes. Thank you. I will fix that once I’m back home. I’m in an airport right
now.

David

**Comment by dj-on-github** [comment]
Fixed
