### ISSUE TITLE
any way to run with python2.6?!

### ISSUE THREAD

**Issue by mhajim** [dj-on-github/sp800_22_tests#4]
Hi, 
any way to run with python2.6?! I use Python 2.6.6 on centos 6

 ./sp800_22_tests.py /tmp/megabitrand.bin
Tests of Distinguishability from Random
TEST: monobit_test
  Ones count   = 523749
  Zeroes count = 524827
Traceback (most recent call last):
  File "./sp800_22_tests.py", line 132, in <module>
    (success,p,plist) = func(bits)
  File "/root/git/sp800_22_tests/sp800_22_monobit_test.py", line 44, in monobit_test
    p = math.erfc(float(s)/(math.sqrt(float(n)) * math.sqrt(2.0)))
AttributeError: 'module' object has no attribute 'erfc'

**Comment by dj-on-github** [comment]
You would need to find an alternative implementation of erfc (complementary error function). I will take a look at the options.

**Comment by dj-on-github** [comment]
See here for examples of how to implement erfc in obsolete versions of python.. https://www.sciencedirect.com/science/article/pii/S0890540112000697
