### ISSUE TITLE
Why a bad random number collection sample can pass the test?

### ISSUE THREAD

**Issue by greendow** [dj-on-github/sp800_22_tests#6]
Hi ! Thank you for sharing your programs on GitHub ! It's a useful tool.
    In the first, I suggest that sp800_22_tests programs be indicated to use in Python 2.7 in a prominent position of the web page on GitHub. They can't be run in Python 2.6. After a slight transform, they can be run in Python 3. The steps of transform are:
   Transform 'print' to the function form, that is, 'print( )' in all python files ;
   Transform 'xrange' to 'range' in all python files;
    In file 'sp800_22_dft_test.py', Line 37:     mags = abs(fs)[:n/2] # Compute magnitudes of first half of sequence
    Transform 'n/2' to 'n//2', that is, mags = abs(fs)[:n//2]
    In file 'sp800_22_tests.py', Line 36:    byte = ord(bytech)
Transform 'ord(bytech)' to 'bytech', that is,  byte = bytech
    After finishing the above modification, I can run the programs successfully in Python 3.6.5.
    Next, NIST provides a tool on web site: https://csrc.nist.gov/CSRC/media/Projects/Random-Bit-Generation/documents/sts-2_1_2.zip
   In the zip file there are some random number samples. Especially, in \sts-2.1.2\data there are three binary data sample files: BBS.dat, data_bad_rng, data.sha1. I tested the three files by python programs. MemoryError was reported while testing BBS.data file, maybe the file size is too big.  The file data.sha1 can pass the test. To my surprise,  the file data.bad_rng can pass the test. In my opinion, data.bad_rng  is a negative example to demonstrate bad randomness. I wonder why such a bad random number collection sample given by NIST can pass the test. Thanks a lot !

**Comment by greendow** [comment]
I paste the test result of data.bad_rng here:

python sp800_22_tests.py data.bad_rng
Tests of Distinguishability from Random
TEST: monobit_test
  Ones count   = 6293375
  Zeroes count = 6289537
  PASS
  P=0.27926677563246316
TEST: frequency_within_block_test
  n = 12582912
  N = 99
  M = 127100
  PASS
  P=0.09336347331162267
TEST: runs_test
  prop  0.5001525084177653
  tau  0.000563818622255494
  vobs  6291081.0
  PASS
  P=0.8328076916803193
TEST: longest_run_ones_in_a_block_test
  n = 12582912
  K = 6
  M = 10000
  N = 75
  chi_sq = 6.417890628197924
  PASS
  P=0.37803996441484977
TEST: binary_matrix_rank_test
  Number of blocks 12288
  Data bits used: 12582912
  Data bits discarded: 0
  Full Rank Count  =  3639
  Full Rank -1 Count =  7024
  Remainder Count =  1625
  Chi-Square =  3.236003808883187
  PASS
  P=0.1982945149024955
TEST: dft_test
  N0 = 5976883.200000
  N1 = 5976281.000000
  PASS
  P=0.11926224101410299
TEST: non_overlapping_template_matching_test
  PASS
  P=1.0001709168939341
TEST: overlapping_template_matching_test
  B =  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  m =  10
  M =  1062
  N =  968
  K =  5
  model =  [352, 179, 134, 97, 68, 135]
  v[j] =   [577, 154, 93, 47, 40, 57]
  chisq =  3.0904097991627153
  PASS
  P=0.686049540749603
TEST: maurers_universal_test
  sum = 11446482.653792728
  fn = 9.171486304480128
  PASS
  P=0.999635018571148
TEST: linear_complexity_test
  M =  512
  N =  24576
  K =  6
  chisq =  7.197653001517425
  P =  0.30295467600347076
  PASS
  P=0.30295467600347076
TEST: serial_test
  psi_sq_m   =  5.879981994628906
  psi_sq_mm1 =  3.8405113220214844
  psi_sq_mm2 =  2.386251449584961
  delta1     =  2.039470672607422
  delta2     =  0.5852108001708984
  P1         =  0.9797778482137055
  P2         =  0.9646928402650262
  PASS
P=0.9797778482137055
P=0.9646928402650262
TEST: approximate_entropy_test
  n         =  12582912
  m         =  3
  Pattern 1 of 8, count = 1571577
  Pattern 2 of 8, count = 1572420
  Pattern 3 of 8, count = 1571892
  Pattern 4 of 8, count = 1573648
  Pattern 5 of 8, count = 1572420
  Pattern 6 of 8, count = 1573120
  Pattern 7 of 8, count = 1573648
  Pattern 8 of 8, count = 1574187
  phi(3)    = -4.382026
  Pattern 1 of 16, count = 785502
  Pattern 2 of 16, count = 786075
  Pattern 3 of 16, count = 785774
  Pattern 4 of 16, count = 786646
  Pattern 5 of 16, count = 785441
  Pattern 6 of 16, count = 786451
  Pattern 7 of 16, count = 786669
  Pattern 8 of 16, count = 786979
  Pattern 9 of 16, count = 786075
  Pattern 10 of 16, count = 786345
  Pattern 11 of 16, count = 786118
  Pattern 12 of 16, count = 787002
  Pattern 13 of 16, count = 786979
  Pattern 14 of 16, count = 786669
  Pattern 15 of 16, count = 786979
  Pattern 16 of 16, count = 787208
  phi(3)    = -5.075174
  AppEn(3)  = 0.693147
  ChiSquare =  2.0400226386263967
  PASS
  P=0.9797602509784263
TEST: cumulative_sums_test
PASS
  PASS
P=0.5479436792261341
P=0.21381709078864475
TEST: random_excursion_test
J=3593
x = -4  chisq = 2.361661        p = 0.797170
x = -3  chisq = 3.506401        p = 0.622419
x = -2  chisq = 6.180588        p = 0.289041
x = -1  chisq = 0.678095        p = 0.984149
x = 1   chisq = 9.283246        p = 0.098286
x = 2   chisq = 1.397234        p = 0.924616
x = 3   chisq = 11.031309       p = 0.050763
x = 4   chisq = 6.117663        p = 0.294938
PASS
  PASS
P=0.7971695436060596
P=0.6224193195000202
P=0.2890414524667669
P=0.9841493521556501
P=0.09828594839747112
P=0.9246156507056988
P=0.05076273458314307
P=0.2949376540231652
TEST: random_excursion_variant_test
J= 3593
x = -9   count=3501     p = 0.186125
x = -8   count=3525     p = 0.146455
x = -7   count=3395     p = 0.458073
x = -6   count=3314     p = 0.701696
x = -5   count=3418     p = 0.486584
x = -4   count=3459     p = 0.422471
x = -3   count=3489     p = 0.387962
x = -2   count=3543     p = 0.240797
x = -1   count=3582     p = 0.091756
x = 1    count=3647     p = 0.450438
x = 2    count=3647     p = 0.260061
x = 3    count=3565     p = 0.104451
x = 4    count=3488     p = 0.331041
x = 5    count=3430     p = 0.453219
x = 6    count=3327     p = 0.669001
x = 7    count=3231     p = 0.837487
x = 8    count=3274     p = 0.687047
x = 9    count=3320     p = 0.552306
PASS
  PASS
P=0.18612502212694923
P=0.14645516043485104
P=0.45807322755686475
P=0.7016964129393772
P=0.4865844094745336
P=0.4224712640024134
P=0.3879624853823026
P=0.2407968341087975
P=0.09175591721519777
P=0.4504381390564254
P=0.2600605808375013
P=0.10445143837215838
P=0.3310409158227866
P=0.4532186213962799
P=0.6690008811536715
P=0.8374874160383082
P=0.6870470026281983
P=0.5523057721810558


SUMMARY
-------
monobit_test                             0.27926677563246316 PASS
frequency_within_block_test              0.09336347331162267 PASS
runs_test                                0.8328076916803193 PASS
longest_run_ones_in_a_block_test         0.37803996441484977 PASS
binary_matrix_rank_test                  0.1982945149024955 PASS
dft_test                                 0.11926224101410299 PASS
non_overlapping_template_matching_test   1.0001709168939341 PASS
overlapping_template_matching_test       0.686049540749603  PASS
maurers_universal_test                   0.999635018571148  PASS
linear_complexity_test                   0.30295467600347076 PASS
serial_test                              0.9646928402650262 PASS
approximate_entropy_test                 0.9797602509784263 PASS
cumulative_sums_test                     0.21381709078864475 PASS
random_excursion_test                    0.05076273458314307 PASS
random_excursion_variant_test            0.09175591721519777 PASS

**Comment by dj-on-github** [comment]
I'll take a look. Don't assume the tests are actually good. I've got them to pass all sorts of bad data. These are the tests the government deemed suitable.

**Comment by dj-on-github** [comment]
I stuck with 2.7 until I was done writing my book. That's done now and I'm converting everything to Python 3. Thanks for your list of changes. I'll apply them.

**Comment by greendow** [comment]
Thank you for your reply! I hope the parameters can be adjusted to make the testing rules stricter if possible. If the testing programs can report similar results in accordance with the NIST test suit (for example, data.sha1 file can pass the test and data.bad_rng cannot pass the test), that may be better. Thanks again!

**Comment by dj-on-github** [comment]
I've pushed the python 2-3 changes. It's now compatible with both python2 and 3.
