### ISSUE TITLE
Typo in Monobit test ?

### ISSUE THREAD

**Issue by karthikkrishnanv** [dj-on-github/sp800_22_tests#8]
`success = (p >= 0.1)
    return (success,p,None)`

Monobit test checks against 0.1. It should be 0.01 right ?

Another failure I see is if you pass same values as test. For example
`bits = np.random.randint(1, size=1000)`

Traceback (most recent call last):
  File "randomness_check.py", line 103, in <module>
    success,p,plist = func(bits)
  File "/Users/karthik/sp800_22_tests/sp800_22_approximate_entropy_test.py", line 73, in approximate_entropy_test
    sum += Ci[i]*math.log((Ci[i]/10.0))
ValueError: math domain error

**Comment by dj-on-github** [comment]
Yes. I've fixed it. I'll push the changes shortly.
Thank you.

**Comment by dj-on-github** [comment]
Fixed.
