### ISSUE TITLE
About Overlapping Template Matching Test

### ISSUE THREAD

**Issue by greendow** [dj-on-github/sp800_22_tests#9]
in sp800_22_overlapping_template_matching_test.py
line 52 :    M = 1062
line 54 :   print("Insufficient data. %d bit provided. 1,028,016 bits required" % len(bits))
but in NIST SP 800-22 Revision 1a, 2.8.2 Function Call :
M    The length in bits of a substring of ε to be tested. M has been set to 1032 in the test code.

So I think it should be :
line 52 :  M = 1032
line 54 :  print("Insufficient data. %d bit provided. 998,976 bits required" % len(bits))

**Comment by dj-on-github** [comment]
The SP800-22 rev1a overlapping test text in the spec is messed up. Section 2.8.7 requires the input data size to be at least 1,000,000 bits. With M=1032 and N = 968 as suggested in the spec, the number of bits analyzed is 998,976 which violates the input size recommendation. 1062 is the smallest M that results in the input size recommendation being met. This is covered in section 10.6.2 of my book - Random Number Generators, Princples and Practices. This error is one of many in the spec that my book covers.

**Comment by dj-on-github** [comment]
Closing this issue. We need for NIST to fix the spec. The code is fine.
